AllCops:
  TargetRubyVersion: 2.3.5
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'log/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/factories/*.rb'